---
title: 'Simulation of Fluidigm Biomark qPCR data - For verification of analysis scripts'
author: "Samuel O Skinner"
date: "March 31, 2017"
output:
  html_document:
    number_sections: yes
---


```{r global_opts, echo=FALSE, cache=FALSE}
knitr::opts_chunk$set(fig.width=8, fig.height=4, fig.align='center',
                      echo=TRUE, warning=FALSE, message=FALSE,
                      cache=FALSE, autodep=TRUE)
# knitr::opts_knit$set(root.dir = "..")

## numbers >= 10^5 will be denoted in scientific notation,
## and rounded to 2 digits
options(scipen = 1, digits = 5)
```

# Setup

## Prepare workspace


``` {r setup}

# R code to start with Fluidigm Ct data and return delta delta Ct values
path<-"~/Box Sync/Projects/Fluidigm_qPCR_analysis/"
directory<-"P142-2_Wambre_IL33_impact"

workdir<-paste(path, directory, "/", sep="")

library(knitr)
library(shiny)
library(ggplot2)
library(reshape2)
library(cowplot)
library(xlsx)

# read in scripts
source(file=paste(workdir,"scripts/","Fluidigm_R_Functions.R",sep=""))
source(file=paste(workdir,"scripts/","Fluidigm_R_HKgenes_Functions.R",sep=""))


``` 

## Load sample data files as a template

```{r read in parameters, echo=FALSE}


# read in all data files stored in Data directory - do not know how many there will be 
fileNames<-list.files(path=paste(workdir,"DataSubset1/",sep=""))
fileNames<-reorderFileNames(fileNames)

# Read in one raw data file and keep on hand for the headers and such
rawData<-read.csv(file=paste(workdir,"DataSubset1/", fileNames[1],sep=""), skip=0)


# read in data (from analysis script)
dataList<-list()
for (i in 1:length(fileNames))
{
	dataList[[i]]<-readFluidData(paste(workdir,"DataSubset1/",fileNames[i],sep=""))
}
names(dataList)<-fileNames


# now check chamber IDs to make sure samples and genes match across plates
# if they do not match, then stop processing - need to fix the input data
anyError <- checkSampleGeneChamberIDs(dataList)
print(paste("Errors detected:", anyError))


# convert into matrix of rows (assays/genes) and columns (samples represented by chamber IDs)
ctValList<-list()
ctCallList<-list()
for (i in 1:length(dataList))
{
	ctValList[[i]]<-changeFluidFormat(dataList[[i]], colName="Ct.Value")
	ctCallList[[i]]<-changeFluidFormat(dataList[[i]], colName="Ct.Call")
}

# Extract and combine data from multiple plates
retList<-combineDataFromMultiplePlates(dataList, ctValList, ctCallList)

```

# Make samples data set

## Set the parameters of numbers of genes / plates

```{r make data set}

# Define dimensions, and gene sets
num_genes <- 96
num_samples <- 96
num_plates <- 2

# Per plate, the make-up of neg, ref, and normal samples
num_ref_samples <- 3
num_neg_samples <- 6
num_bio_samples <- num_samples - num_ref_samples - num_neg_samples

# Per gene panel, the number of HK genes
num_HK_genes <- 3
num_bio_genes <- num_genes - num_HK_genes

# Number of sample groups and gene sets
num_sample_groups <- 2
num_gene_sets <- 3

```


## Initialize single plate (from rawdata)

```{r init plate}

# Gene panel
panel <- rawData$GE.96x96.Fast.PCR.Melt.v2[12:107]

# Set up structure of Ct values
cts <- matrix(data=NA, ncol=num_genes, nrow=num_samples)
rownames(cts) <- panel
colnames(cts) <- c(paste("Sample", seq(1:num_bio_samples), sep=""), 
                   paste("Ref", seq(1:num_ref_samples), sep=""), 
                   paste("Neg", seq(1:num_neg_samples), sep=""))

```


# Define sample groups and gene sets

```{r samples and genes}

# Sample groups
sample_groups <- list()
samples <- seq(1:num_bio_samples)
if (num_sample_groups==1) {
  sample_groups[[1]] <- samples
} else {
  for (group in 1:(num_sample_groups-1)) {
    sample_groups[[group]] <- sample(samples, size=round(num_bio_samples/num_sample_groups))
    samples <- samples[!(samples %in% sample_groups[[group]])]
  }
  sample_groups[[num_sample_groups]] <- samples
}

# Gene sets
gene_sets <- list()
genes <- seq(1:num_bio_genes)
if (num_gene_sets==1) {
  gene_sets[[1]] <- genes
} else {
  for (set in 1:(num_gene_sets-1)) {
    gene_sets[[set]] <- sample(genes, size=round(num_bio_genes/num_gene_sets))
    genes <- genes[!(genes %in% gene_sets[[set]])]
  }
  gene_sets[[num_gene_sets]] <- genes
}

# Reference and negative samples
ref_samples <- seq((num_bio_samples+1),(num_bio_samples+num_ref_samples))
neg_samples <- seq((num_bio_samples+num_ref_samples+1), num_samples)

# Housekeeping genes
HK_genes <- seq((num_bio_genes+1), num_genes)

```

## Define the expression pattern for the sample groups and gene sets

```{r exp pattern}

# Fill in reference samples 
cts[c(unlist(gene_sets), HK_genes),ref_samples] <- 25

# Fill in housekeeping genes
cts[HK_genes,c(unlist(sample_groups), ref_samples)] <- 45

# Fill in the negatives
cts[,neg_samples] <- 1

# Fill in the samples to investigate
num_patterns <- num_gene_sets * num_sample_groups
patterns <- 10*seq(1,num_patterns)
i <- 1
for (group in 1:num_sample_groups) {
  # group = 2
  for (set in 1:num_gene_sets) {
    # set = 3
    cts[gene_sets[[set]],sample_groups[[group]]] <- patterns[i]
    i <- i+1
  }
}

```


# Save as csv files

```{r save files}

cts_long <- melt(cts)

# Add in the sample names to the data csv
rawData$S..Fluidigm.Data.P142.Th2A.Th2.ILC2.Anaptys.qPCR...Erik.P142.2.P142.2_S2A1_1362055191_6335.FDGP.16_28Dec2016.ChipRun.bml[12:(11+dim(cts_long)[1])] <- cts_long$Var2

# Add in the values to the data csv
rawData$EvaGreen[12:(11+dim(cts_long)[1])] <- cts_long$value

# Write out the simulated data
write.xlsx(rawData, 
           file="/Users/samskinner/Box Sync/Projects/simulatedata_qpcrbiomark/data/simulated_data_output.xlsx",
           row.names = FALSE)

```

